#set-option -g default-command "reattach-to-user-namespace -l zsh"
#set -g default-terminal "screen-256color"
set -g history-limit 20000

# use VI
set-window-option -g mode-keys vi

# kill
unbind k
bind C-k command-prompt "kill-window"

unbind ^x
bind ^x kill-pane

# Vim Select Pane
unbind h
bind h select-pane -L
unbind j
bind j select-pane -D
unbind k
bind k select-pane -U
unbind l
bind l select-pane -R

# Copy mode works like Vim
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer

bind -t vi-copy 'v' begin-selection
bind -t vi-copy 'V' rectangle-toggle
bind -t vi-copy y copy-selection
bind y send-keys y\;\
       run-shell "tmux save-buffer - | reattach-to-user-namespace pbcopy"

# Clear screen and scrollback
#bind -n C-k send-keys -R \; clear-history

# cycle through panes
unbind ^A
bind ^A select-pane -t :.+

unbind Right
bind Right resize-pane -R 8
unbind Left
bind Left resize-pane -L 8
unbind Up
bind Up resize-pane -U 4
unbind Down
bind Down resize-pane -D 4

# reload config
unbind r
bind r source-file ~/.tmux.conf

unbind ^T
bind ^T split-window -p 25

# horizontal and vertical splits
unbind |
bind | split-window -h
unbind _
bind _ split-window


set -g status on
set -g status-utf8 on
set -g status-interval 2
set -g status-fg colour231
set -g status-bg colour234
set -g status-left-length 50
set -g status-left '#[fg=colour16,bg=colour254,bold] #S #[fg=colour254,bg=colour234,nobold]#(/usr/local/bin/powerline tmux left)'
set -g status-right '#(/usr/local/bin/powerline tmux right)'
set -g status-right-length 150
set -g window-status-format "#[fg=colour244,bg=colour234]#I #[fg=colour240] #[fg=colour249]#W "
set -g window-status-current-format "#[fg=colour234,bg=colour31]#[fg=colour117,bg=colour31] #I  #[fg=colour231,bold]#W #[fg=colour31,bg=colour234,nobold]"
##### COLOUR (Solarized dark)

# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour130 #yellow
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour33 #base0
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour196 #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour46 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour196 #orange

## pane number display
set-option -g display-panes-active-colour colour20 #blue
set-option -g display-panes-colour colour196 #orange

## clock
set-window-option -g clock-mode-colour colour40 #green

#source /usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/powerline.conf
#set-option -g default-terminal "term-256color"

## tmuxline config file
if-shell "test -f ~/.tmuxline.conf" "source ~/.tmuxline.conf"
