#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive
rm -f ~/.zshrc
ln -s ~/.dotfiles/.zshrc ~/.zshrc

sudo cpan Term::ExtendedColor
git clone git://github.com/trapd00r/ls--.git
cd ls--
perl Makefile.PL
make && sudo 'make install'

cp ls++.conf $HOME/.ls++.conf
cd ~/
